#!/bin/sh
# -*- mode: sh -*-

##
# baseline
set -e

##
# vars
destdir="${1}"

##
# main
if [ -e "${destdir}" ]; then
    chmod 750 "${destdir}"
fi
if [ -e "${destdir}"/bin ]; then
    find "${destdir}"/bin  -type f -exec chmod 750 {} \;
fi
if [ -e "${destdir}"/.ssh ]; then
    find "${destdir}"/.ssh -type d -exec chmod 700 {} \;
    find "${destdir}"/.ssh -type f -exec chmod 600 {} \;
fi
