#!/bin/sh
set -e

#
# globals
#
localbase="$(dirname "${0}")/../../.."
user="_bones"

#
# functions
#
bindir()
{
    if [ "$(uname)" = "Linux" ]; then
        echo "/bin"
    else
        echo $(realpath "${localbase}")/bin
    fi
}

#
# main
#
doas -u "${user}" -n -- "$(bindir)"/git "${@}"
exit "${?}"
