#!/bin/sh
set -e

##
# vars
localbase="${LOCALBASE:-/usr/local}"
user="_bones"
bindir=""

##
# functions
choose_bindir()
{
    if [ "$(uname)" = "Linux" ]; then
        echo "/bin"
    else
        echo "${localbase}"/bin
    fi
}

##
# main
bindir=$(choose_bindir)
doas -u "${user}" -n -- "${bindir}"/git "${@}"
exit "${?}"
