#!/bin/sh
set -e

##
# globals
repodir="${1}"
destdir="${2}"
file="${3}"
destination="${destdir}"/"${file}"
source="${repodir}"/"${file}"

##
# functions
libexec="$(dirname "${0}")/.."
. "${libexec}"/functions/print.sh

##
# main
if [ -e "${destination}" ]; then
    if [ "$(cat "${destination}")" = "" ]; then
        install -m 644 "${source}" "${destination}"
    elif cmp -s "${destination}" "${source}"; then
        printok "nothing to do"
    else
        temp=$(mktemp)
        sdiff -o "${temp}" "${source}" "${destination}" < "/dev/tty" || true
        install -m 644 "${temp}" "${destination}"
        rm "${temp}"
    fi
else
    install -m 644 "${source}" "${destination}"
fi
