#!/bin/sh
set -e

##
# vars
sourcedir="${1}"
destdir="${2}"
file="${3}"
tty="/dev/tty"
dest=""
temp=""

##
# functions
run_install()
{
    local source="${1}"
    local dest="${2}"
    local mode="644"
    install -m "${mode}" "${source}" "${dest}"
    echo "bones: install -m ${mode} ${source} ${dest}"
}

##
# main
dest="${destdir}"/"${file}"
file="${sourcedir}"/"${file}"
if [ -e "${dest}" ]; then
    if [ "$(cat "${dest}")" = "" ]; then
        run_install "${file}" "${dest}"
    elif ! cmp -s "${dest}" "${file}"; then
        temp=$(mktemp)
        sdiff -o "${temp}" "${file}" "${dest}" < "${tty}" || true
        run_install "${temp}" "${dest}"
        rm "${temp}"
    else
        echo "bones: nothing to do"
    fi
else
    run_install "${file}" "${dest}"
fi
