#!/bin/sh
set -e

#
# globals
#
destdir="${1}"
user="${2}"
group="${3}"

#
# functions
#
. "$(dirname "${0}")/.."/functions/print.sh

#
# main
#
if [ -e "${destdir}" ]; then
    chmod 750 "${destdir}"
    chown -R "${user}":"${group}" "${destdir}"
fi
if [ -e "${destdir}"/bin ]; then
    find "${destdir}"/bin  -type f -exec chmod 750 {} \;
fi
if [ -e "${destdir}"/.ssh ]; then
    find "${destdir}"/.ssh -type d -exec chmod 700 {} \;
    find "${destdir}"/.ssh -type f -exec chmod 600 {} \;
fi
