#!/bin/sh
set -e

##
# globals
localbase="$(dirname "${0}")"/../../..
sharedir="${localbase}"/share/bones

##
# functions
. "$(dirname "$0")"/../functions/print.sh

source()
{
    if [ "$(uname)" = "Linux" ]; then
        echo "${sharedir}"/Linux/doas.conf
    else
        echo "${sharedir}"/BSD/doas.conf
    fi
}

destination()
{
    if [ "$(uname)" = "FreeBSD" ]; then
        echo "${LOCALBASE:-/usr/local}"/etc/doas.conf
    else
        echo "/etc/doas.conf"
    fi
}

##
# main
if [ -e "$(destination)" ]; then
    cat "$(source)" |
    while read -r line; do
        if grep -q "${line}" "$(destination)"; then
            continue
        fi
        echo "${line}" >> "$(destination)"
    done
else
    install -m 600 \
            -o root \
            -g wheel \
            "$(source)"  \
            "$(destination)"
fi
printok "add $(destination)"
