#!/bin/sh
set -e

##
# vars
localbase="$(dirname "${0}")"/../../..
libexec="$(dirname "$0")"/..
sharedir="${localbase}"/share/bones
src=""
dest=""

##
# functions
. "${libexec}"/functions/print.sh

choose_source()
{
    if [ "$(uname)" = "Linux" ]; then
        echo "${sharedir}"/Linux/doas.conf
    else
        echo "${sharedir}"/BSD/doas.conf
    fi
}

choose_destination()
{
    if [ "$(uname)" = "FreeBSD" ]; then
        echo "${LOCALBASE:-/usr/local}"/etc/doas.conf
    else
        echo "/etc/doas.conf"
    fi
}

##
# main
src=$(choose_source)
dest=$(choose_destination)
if [ -e "${dest}" ]; then
    # shellcheck disable=SC2002
    cat "${src}" |
    while read -r line; do
        if grep -q "${line}" "${dest}"; then
            continue
        fi
        echo "${line}" >> "${dest}"
    done
else
    install -m 600 \
            -o root \
            -g wheel \
            "${src}"  \
            "${dest}"
fi
printok "add ${dest} (double check it!)"
