#!/bin/sh
set -e

#
# globals
#
user="_bones"

#
# functions
#
. "$(dirname "$0")"/../functions/print.sh

#
# main
#
if ! id -u "${user}" > /dev/null 2>&1; then
    if which pw > /dev/null 2>&1; then
        pw useradd       \
           -n "${user}"   \
           -c "bones user" \
           -M 750           \
           -m                \
           -s /sbin/nologin
    elif which useradd > /dev/null 2>&1; then
        if [ "$(uname)" = "Linux" ]; then
            useradd               \
                -d /home/"${user}" \
                -c "bones user"     \
                -m                   \
                -s /sbin/nologin      \
                "${user}"
        else
            # Hello (Net|Open)BSD
            useradd               \
                -d /home/"${user}" \
                -v                  \
                -m                   \
                -s /sbin/nologin      \
                "${user}"
        fi
        chmod 750 /home/"${user}"
    else
        printerr "$(uname) is not supported"
        exit 1
    fi

fi
find /home/"${user}" -type f -exec rm {} \;
printok "add user"
