#!/bin/sh
set -e

##
# globals
repourl="${1}"
repodir="/home/_bones/.local/share/skeletons"
git="$(dirname "${0}")/.."/scripts/git
mkdir="$(dirname "${0}")/.."/scripts/mkdir

##
# functions
. "$(dirname "${0}")/.."/functions/print.sh

##
# main
if [ -z "${repourl}" ]; then
    printerr "provide a repository url"
    exit 1
elif [ ! -e "${repodir}" ]; then
    "${mkdir}" -m 750 -p "${repodir}"
fi

cd "${repodir}"
if "${git}" clone "${repourl}" "${repodir}"; then
    printok "clone complete"
else
    rc="${?}"
    printerr "unexpected clone error"
    exit "${rc}"
fi
