#!/bin/sh

##
# vars
repourl="${1}"
sourcedir="${XDG_DATA_HOME:-${HOME}/.local/share}/bones/"
basename="$(basename "${repourl}" .git)"

##
# main
if [ ! -e "${sourcedir}" ]; then
    mkdir -m 750 -p "${sourcedir}"
fi
if git clone "${repourl}" "${sourcedir}"/"${basename}"; then
    echo "bones: clone complete"
else
    rc="${?}"
    echo "bones: unexpected clone error"
    exit "${rc}"
fi
