#!/bin/sh
set -e

##
# vars
basename="$(echo "${1}" | sed 's|:|/|')"
destdir="${2}"
libexec="$(dirname "${0}")/.."
sourcedir="${BONES_HOME:-${HOME}/.local/share}/bones/${basename}"
user=$(id -n -u)
group=$(id -n -g)

##
# functions
. "${libexec}"/functions/print.sh

parse_options()
{
    while getopts u:g: opt; do
        if [ "${opt}" = "u" ]; then
            user="${OPTARG}"
        elif [ "${opt}" = "g" ]; then
            group="${OPTARG}"
        else
            exit 1
        fi
    done
}

##
# main
if [ -z "${basename}" ]; then
    printerr "provide a skeleton or bone"
    exit 1
elif [ -z "${destdir}" ]; then
    printerr "provide the path to a target"
    exit 1
elif [ -d "${sourcedir}" ]; then
    shift 2
    parse_options "${@}"
    find "${sourcedir}" -type d -mindepth 1 |
    sed "s|${sourcedir}/||" |
    while read -r dir; do
        mkdir -m 750 -p "${destdir}"/"${dir}"
        printok "mkdir -m 750 -p ${destdir}/${dir}"
    done
    find "${sourcedir}" -type f -mindepth 1 |
    sed "s|${sourcedir}/||" |
    while read -r file; do
        "${libexec}"/scripts/install "${sourcedir}" "${destdir}" "${file}"
    done
    "${libexec}"/scripts/finalize "${destdir}" "${user}" "${group}"
else
    printerr "${sourcedir} is not a directory"
    exit 1
fi
