#!/bin/sh
set -e

##
# vars
basename="${1}"
destdir=$(realpath "${2}")
sourcedir="${BONES_HOME:-${HOME}/.local/share}/bones/${basename}"
libexec=$(realpath "$(dirname "${0}")/..")

##
# main
if [ -d "${sourcedir}" ]; then
    find "${sourcedir}" -type d -mindepth 1 |
    sed "s|${sourcedir}/||" |
    while read -r dir; do
        mkdir -m 750 -p "${destdir}"/"${dir}"
        echo "bones: mkdir -m 750 -p $(realpath "${destdir}"/"${dir}")"
    done
    find "${sourcedir}" -type f -mindepth 1 |
    sed "s|${sourcedir}/||" |
    while read -r file; do
        "${libexec}"/scripts/install "${sourcedir}" "${destdir}" "${file}"
    done
    "${libexec}"/scripts/finalize "${destdir}"
else
    echo "bones: ${sourcedir} is not a directory"
    exit 1
fi
