#!/bin/sh
set -e

##
# globals
dirname="${1}"
destdir="${2}"
repodir="/home/_bones/.local/share/skeletons/${dirname}"
user="$(id -n -u)"
group="$(id -n -g)"

##
# functions
. "$(dirname "${0}")/.."/functions/print.sh

parse_options()
{
    while getopts u:g: opt; do
        if [ "${opt}" = "u" ]; then
            user="${OPTARG}"
        elif [ "${opt}" = "g" ]; then
            group="${OPTARG}"
        else
            exit 1
        fi
    done
}

create_directories()
{
    find "${repodir}" -type d -mindepth 1 |
    sed "s|${repodir}/||" |
    while read -r dir; do
        mkdir -m 750 -p "${destdir}"/"${dir}"
    done
    printok "create directories"
}

install_files()
{
    find "${repodir}" -type f -mindepth 1 |
    sed "s|${repodir}/||" |
    while read -r file; do
        "$(dirname "${0}")/.."/scripts/install "${repodir}" "${destdir}" "${file}"
    done
    printok "install files"
}

set_permissions()
{
    "$(dirname "${0}")/.."/scripts/set-permissions "${destdir}" "${user}" "${group}"
    printok "set permissions"
}

##
# main
if [ -z "${destdir}" ]; then
    printerr "provide the path to a target"
    exit 1
elif [ -d "${repodir}" ]; then
    shift 2
    parse_options "${@}"
    create_directories
    install_files
    set_permissions
else
    printerr "${repodir} is not a directory"
    exit 1
fi
