#!/bin/sh
set -e

##
# vars
basename="${1}"
libexec="$(dirname "${0}")/.."
sourcedir="/home/_bones/.local/share/${basename}"
branch=""

##
# functions
. "${libexec}"/functions/print.sh

##
# main
if [ -z "${basename}" ]; then
    printerr "provide the name of a skeleton"
    exit 1
else
    cd "${sourcedir}"
    branch=$("${libexec}"/scripts/git branch --show-current)
    "${libexec}"/scripts/git pull --rebase origin "${branch}"
fi
